repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: detect-private-key


- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [--strict, --force-scope, feat, fix, chore, test, custom, ci, refactor]

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.11.0
  hooks:
  - id: shellcheck

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.29.0
  hooks:
    - id: gitleaks

- repo: https://github.com/jamescherti/pre-commit-elisp
  rev: v1.0.5
  hooks:
    - id: elisp-check-parens
    - id: elisp-check-byte-compile
    - id: elisp-indent
