#!/bin/bash

# VS Code 
export EDITOR='code --wait'

# Extend PATH
export PATH=~/.local/bin:$PATH

alias kube="~/.local/bin/kubectl"
alias k="~/.local/bin/kubectl"

# Export Workplace/
export WORKSPACE=~/Workspace
export REPOS="$WORKSPACE/Repos"
export LOGS="$WORKSPACE/Logs"

# Source external configurations
source ~/Workspace/Repos/naranja/dotfiles/functions
