#!/bin/bash 
# Aliases file
#

# Variables
DOTFILES_DIR=${HOME}/.dotfiles
CONFIG_DIR=${DOTFILES_DIR}/config
ALIASES_DIR=${DOTFILES_DIR}/private 

if [[ -d "${ALIASES_DIR}" ]] ; then
  for file in $(ls -1 $ALIASES_DIR | grep alias); do
    source ${ALIASES_DIR}/${file}
  done
fi

# Check OS type and export coloured `ls`
case "$(uname -s)" in
  Darwin)
  alias ls='ls -G'
  alias l='ls -laG'
  alias ll='ls -ltrG'
  ;;
  Linux)
  alias ls='ls --color=auto'
  alias l='ls -la --color=auto'
  alias ll='ls -ltr --color=auto'
  ;;
  CYGWIN*|MINGW32*|MSYS*|MINGW*)
  echo 'MS Windows'
  ;;
  
  *)
  echo 'Other OS' 
  ;;
esac

# Editor config
#
#
export EDITOR='nvim'
alias vim='nvim'
alias view='nvim -R'

#
# Environment config
#
export PATH=~/.local/bin:$PATH
export WORKSPACE=~/Workspace
export REPOS="$WORKSPACE/Repos"
export LOGS="$WORKSPACE/Logs"

alias kube="/usr/local/bin/kubectl"
alias k="/usr/local/bin/kubectl"

#
# Git 
#
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'

# Source external configurations
source ~/.dotfiles/functions/git.sh 
source ~/.dotfiles/functions/kubernetes.sh
source ~/.dotfiles/functions/terraform.sh
source ~/.dotfiles/functions/aws.sh

# Frecuently used config files
alias vimrc="nvim ${CONFIG_DIR}/neovim/init.vim"
alias zshrc="nvim ${CONFIG_DIR}/zshrc"
alias bashrc="nvim ${CONFIG_DIR}/bashrc"
alias tmuxrc="nvim ${CONFIG_DIR}/tmux.conf"
alias aliasrc="nvim ${CONFIG_DIR}/aliases"
alias dotFiles="cd ~/.dotfiles"
alias devDotFiles="vim ~/.dotfiles"
alias aws-instances='aws ec2 describe-instances | view -'
