# 
# Alejandro's bashrc
#

# vi mode
set -o vi

# 
# BASH customizations
#
export PATH=$PATH:/usr/local/bin:/opt/bin
export DOTFILES=${HOME}/Code/github.com/asajaroff/dotfiles

# History
HISTFILE="${HOME}/.bash_history"
export HISTCONTROL=ignoreboth,erasedups
export HISTTIMEFORMAT="%h %d %H:%M:%S "
export HISTIGNORE="ls:ps:history"
export HISTSIZE=10000000
export SAVEHIST=${HISTSIZE}
shopt -s cmdhist

#
# Aliases
#
source ${DOTFILES}/config/aliases

#
# Functions
#
readarray -t FILES < <(ls -1 $DOTFILES/src/functions/ )

for file in "${FILES[@]}"; do
    echo "$file"
done

#
# EEN 
#
EEN_FUNCTIONS_DIR="${HOME}/.dotfiles/private/een/functions/"
EEN_FUNCTIONS=$(ls -1 ${EEN_FUNCTIONS_DIR})
echo $EEN_FUNCTIONS

if [[ -d ${EEN_FUNCTIONS_DIR} ]]; then

    readarray -t FILES < <(ls -1 $EEN_FUNCTIONS_DIR )

    for file in "${FILES[@]}"; do
	source ${EEN_FUNCTIONS_DIR}/${file}
	echo "Sourced ${file}"
    done
fi

#
# Editor
# 

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='emacs -nw'
fi

# Krew
#
if [[ -d ${HOME}/.krew ]]; then
  export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
fi

# Starship shell
eval "$(starship init bash)"

# Bash completions
. <(asdf completion bash)
. <(tldr --print-completion bash)

# Coloured man pages
export MANPAGER="less -R --use-color -Dd+r -Du+b"
export MANROFFOPT="-P -c"