# 
# Alejandro's bashrc
#

# vi mode
set -o vi

# 
# BASH customizations
#
export PATH=$PATH:/usr/local/bin:/opt/bin
export DOTFILES=${HOME}/Code/github.com/asajaroff/dotfiles

# History
HISTFILE="${HOME}/.bash_history"
export HISTCONTROL=ignoreboth,erasedups
export HISTTIMEFORMAT="%h %d %H:%M:%S "
export HISTIGNORE="ls:ps:history"
export HISTSIZE=10000000
export SAVEHIST=${HISTSIZE}
shopt -s cmdhist

#
# Aliases
#
source ${DOTFILES}/config/aliases

# Functions
source ${DOTFILES}/private/clone.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Starship shell
eval "$(starship init bash)"

# Bash completions
. <(asdf completion bash)
. <(tldr --print-completion bash)

# Coloured man pages
export MANPAGER="less -R --use-color -Dd+r -Du+b"
export MANROFFOPT="-P -c"

