# DESIGN TWEAKS

set -g mouse on
set-option -g history-limit 10000

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
setw -g clock-mode-colour lightblue

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# copy mode
setw -g mode-style 'fg=black bg=lightblue bold'

# Copy to MacOS or xclip
if-shell "uname | grep -q Darwin" {
  bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
  bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
} {
  set -s copy-command 'wl-copy'
  # bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
  # bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
  bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
  bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"
}

## panes
set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=colour208'
set -g pane-border-status top
set -g pane-border-format '#{pane_index}: #{pane_title}'
# rename the current pane's title (shown in the border bar above)
bind P command-prompt -I "#{pane_title}" "select-pane -T '%%'"
#
## statusbar
set -g status-position bottom
#set -g status-justify centre
set -g status-style 'bg=lightgrey fg=black'
#
set -g status-right '#[fg=black]#H  %H:%M'
set -g status-left-length 80
#
#set -g status-right-style 'fg=lightblue bg=black'
## set -g status-right '%a, %d %b %Y %T %z'
#set -g status-right '%a, %d %b %Y %T %z'
#set -g status-right-length 100
#
setw -g window-status-current-style 'fg=colour208 bold'
#setw -g window-status-current-format ' #I #W #F '
#
#setw -g window-status-style 'fg=lightblue bg=black'
#setw -g window-status-format '#I #[fg=white]#W #[fg=yellow]#F'
#
#setw -g window-status-bell-style 'fg=yellow bg=red bold'
#
## messages
set -g message-style 'fg=lightblue bg=black bold'

# windows
set-window-option -g automatic-rename

# This makes emacs evil-mode work with no delay
set -s escape-time 0

# Variable for the TERM env-var
set -g default-terminal "screen-256color"

bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
