name: Make all stages

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - master

jobs:
  stow:
    name: Verify stow packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install dependencies'
        run: sudo apt-get update && sudo apt-get install -y stow
      - name: 'Place checkout at ~/.dotfiles'
        run: ln -sf "${{ github.workspace }}" "${HOME}/.dotfiles"
      - name: 'stow -n -v across all packages'
        run: |
          cd ~/.dotfiles
          stow -n -v -d ~/.dotfiles -t "${HOME}" starship tmux

  lint:
    name: pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: pre-commit/action@v3.0.1

  emacs:
    name: Emacs configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install dependencies'
        run: sudo apt-get update && sudo apt-get install -y emacs gcc cmake

      - name: 'Validate emacs config'
        run: |
          ln -sf ${{ github.workspace }} ${HOME}/.dotfiles
          touch ${HOME}/.emacs.custom.el
          ln -sf ${{ github.workspace }}/config/emacs/init.el ${HOME}/.emacs
          script -q -e -c "emacs --batch --load ~/.dotfiles/config/emacs/init.el --eval '(kill-emacs)'"

  make:
    name: Common Make stages
    runs-on: ubuntu-latest
    steps:

      - name: '[dep] Install dependencies'
        run: sudo apt-get update && sudo apt-get install -y tmux neovim

      - uses: actions/checkout@v2
      - name: 'make emacs'
        run: make shells

      - uses: actions/checkout@v2
      - name: 'Clone private repos'
        run: git submodule update --init --recursive
        continue-on-error: true

      - uses: actions/checkout@v2
      - name: 'make shells'
        run: make shells

      - uses: actions/checkout@v2
      - name: 'make kubernetes'
        run: make kubernetes

      # TODO: Make this work at some point
      #- uses: actions/checkout@v2
      #- name: 'Validate tmux config'
      #  run: tmux source ./config/tmux/.tmux.conf
