name: Make all stages

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - master

jobs:
  emacs:
    name: Emacs configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install dependencies'
        run: sudo apt-get update && sudo apt-get install -y emacs

      - name: 'Makefile validation'
        run: make emacs

      - name: 'Validate emacs config'
        run: emacs -nw --load ~/.dotfiles/config/emacs/init.el --eval '(kill-emacs)'

  make:
    name: Run all Makefile stages
    runs-on: ubuntu-latest
    steps:

      - name: '[dep] Install dependencies'
        run: sudo apt-get update && sudo apt-get install -y tmux neovim

      - uses: actions/checkout@v2
      - name: 'make emacs'
        run: make shells

      - uses: actions/checkout@v2
      - name: 'Clone private repos'
        run: git submodule update --init --recursive
        continue-on-error: true

      - uses: actions/checkout@v2
      - name: 'make shells'
        run: make shells

      - uses: actions/checkout@v2
      - name: 'make kubernetes'
        run: make kubernetes

      # TODO: Make this work at some point
      #- uses: actions/checkout@v2
      #- name: 'Validate tmux config'
      #  run: tmux source ./config/tmux/.tmux.conf