name: Make all targets

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  make:
    name: Run all Makefile stages
    runs-on: ubuntu-latest
    steps:
      - name: '[dep] Install Emacs'
        uses: purcell/setup-emacs@master
        with:
          version: 27.1
      - uses: actions/checkout@v2
      - name: 'Private repository'
        run: git submodule update --init --recursive
        continue-on-error: true
      - uses: actions/checkout@v2
      - name: 'Bash shell config'
        run: make shells
      - uses: actions/checkout@v2
      - name: 'kubernetes utils'
        run: make kubernetes
      - uses: actions/checkout@v2
      - name: 'neovim install'
        run: make neovim

