name: Make all targets

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  make:
    name: Make all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shells
        run: git submodule update --init --recursive
        continue-on-error: true
      - uses: actions/checkout@v2
      - name: shells
        run: make shells
      - uses: actions/checkout@v2
      - name: editor
        run: make editor
